### PR TITLE
Added Timezone - Removed Rev with permission

### PR DESCRIPTION
**Pull request by franc-ist**
Todo:
- [x] Make `!time me` command
- [x] iso3166 code lookup - gives Cont/City
- [x] make `!time tz` work Cont/City
- [x] clarify error messages
- [x] checks for if user hasn't registered
- [x] allow user to look up another user's time

### CODE REVIEW

**Comment by irdumbs** [comment]
lol

**Comment by franc-ist** [comment]
@Twentysix26 updated this pr to be serious

**Comment by franc-ist** [comment]
readded rev

**Comment by franc-ist** [comment]
added `!time me`, as per @irdumbs request. Currently has like 0 functionality

**Comment by franc-ist** [comment]
Added ISO code lookup & user's time lookup

**Pull request closed without merging**
