### PR TITLE
[Welcome] Random welcomes, Bot msg, Bot role (#36)

### PR DESCRIPTION
**Pull request by Chovin**
needs testing. doesn't check if bot has permissions to add role. will just notify user in console when a bot joins
#36

### CODE REVIEW

**Review by Kowlin — CHANGES_REQUESTED** [review]
Error on command `welcomeset bot msg`, errors out when no there is no string in `format_msg`. Possible fix can be sending the help text on the command if empty.

`Error in command 'welcomeset bot msg' - AttributeError: 'NoneType' object has no attribute 'format'`

**Comment by Chovin** [comment]
finally got around to fixing this.
anything else?

**Comment by aikaterna** [comment]
[p]welcomeset msg list only returns non-bot welcomes in the list. 
	*May want to include bot welcome messages under [p]welcomeset bot list
	*May also not be relevant until there's more than one bot welcome message, like the random queue on user welcome messages.

[p]welcomeset bot role with no argument returns `Error in command 'welcomeset bot role' - AttributeError: 'NoneType' object has no attribute 'name'`
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\message_economy.py", line 59, in process_message
    server = message.server.id
AttributeError: 'NoneType' object has no attribute 'id'
```

In the [p]welcomeset bot role [role] help, you may want to add that you need to encapsulate roles with spaces within double quotes.

From a user standpoint, it still has the issue where a bot can't add a bot to it's same permission level - that you mentioned in your first post.

**Comment by Chovin** [comment]
- [x] won't list bot msgs until they are also random
- [ ] welcomeset bot role w/out args -> error
- [ ] help welcomeset bot role -> enclose multiword with spaces
- [ ] check permissions. May not do this yet

**Pull request closed without merging**
