### PR TITLE
Added Fish Insult, instead of extending current insult.

### PR DESCRIPTION
**Pull request by TheDataLeek**
Given the last PR was rejected due to author disagreements, this PR adds functionality (hopefully) without prior author issues.

The original authors have been credited in the info.json file.

In essence, this plugin vastly extends the original insult.json list, improves its readability, and adds support for two different insult APIs.
- http://www.insultgenerator.org/
- http://quandyfactory.com/insult/json

These methods are chosen at random.

### CODE REVIEW

**Comment by Twentysix26** [comment]
The name of the py file must be the same as the folder's name.

Also I'd prefer if you used aiohttp instead of requests. Other than it hanging the whole bot when doing IO it's always good to keep 3rd party libraries to a minimum and only use them when necessary. You can find various aiohttp examples in the bot.

**Comment by TheDataLeek** [comment]
Thanks for your feedback. I'll work on implementing those in the next day or so.

**Comment by TheDataLeek** [comment]
Thanks for your feedback, I've implemented those changes. Please let me know if there's anything else I should do for better integration.

**Comment by Twentysix26** [comment]
`self.insults = fileIO("data/insult/insults.json","load")`

Your cog is still using the files of the other one, not its own.
Also, you might as well remove `check_files()` and `check_folders()`, they're useless since the downloader takes care of them

**Comment by Twentysix26** [comment]
`# Insults are listed here for ease. Separate data file /could/ be added, but it makes installation simpler`

I'm really missing the point of this considering that the user doesn't have to do anything at all to install additional files but whatever

**Pull request merged**
